openapi: 3.0.0
info:
  title: Asvatok API
  description: API for Asvatok API by Gulshan Sharma
  version: 1.0.0
servers:
  - url: https://asvatok.onrender.com
  - url: http://localhost:4000
    description: Main server
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /api/v1/auth/login:
    post:
      summary: User Login
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                  description: User email address.
                password:
                  type: string
                  minLength: 1
                  description: User password.
              required:
                - email
                - password
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '401':
          description: User Not verified please verify first And redirect to verify otp page

  /api/v1/auth/registration:
    post:
      summary: User registration
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                  description: User email address.
                password:
                  type: string
                  minLength: 1
                  description: User password.
                confirmPassword:
                  type: string
                  minLength: 1
                  description: confirm Password.
                name:
                  type: string
                  minLength: 1
                  description: User name.
                mobile:
                  type: string
                  minLength: 1
                  description: Mobile number.
              required:
                - email
                - password
                - confirmPassword
                - name
                - mobile
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

  /api/v1/auth/resend_email:
    post:
      summary: resend email   
      tags:
        - User
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  minLength: 1
                  description: User email address.
              required:
                - email
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request

  /api/v1/member/kyc:
    post:
      summary: Add Kyc
      tags:
        - Kyc
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  description: Name of user.
                address:
                  type: string
                  minLength: 1
                  description: Address of user.
                number:
                  type: string
                  minLength: 1
                  description: Number of user.
                id_num:
                  type: string
                  minLength: 1
                  description: Id number of user document.
                type:
                  type: string
                  minLength: 1
                  description: type of user document.
                a_front:
                  type: string
                  minLength: 1
                  description: Front side of user document.
                a_back:
                  type: string
                  minLength: 1
                  description: Back side of user document.
                pan:
                  type: string
                  minLength: 1
                  description: Pan front of user document.
                pan_back:
                  type: string
                  minLength: 1
                  description: Pan back of user document.
                self_pic:
                  type: string
                  minLength: 1
                  description: Selfie of user.
                sign:
                  type: string
                  minLength: 1
                  description: Signature of user.
              required:
                - name
                - address
                - number
                - id_num
                - type
                - a_front
                - a_back
                - pan
                - pan_back
                - self_pic
                - sign
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error OR authorization header must be provided

  /api/v1/member/get_kyc_status:
    post:
      summary: Get kyc status
      tags:
        - Kyc
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error OR authorization header must be provided

  /api/v1/member/add_profile:
    post:
      summary: Add Profile
      tags:
        - Profile
      requestBody:
        content:
          application/json:
             schema:
               type: object
               properties:
                 aboutMe:
                   type: string
                   minLength: 1
                   description: About me.
                 wallet:
                   type: string
                   minLength: 1
                   description: Wallet.
                 pic:
                  type: string
                  format: 1
                  description: profile pic.
               required:
                 - aboutMe
                 - wallet
                 - pic
      security:
       - BearerAuth: []
      responses:
        '200':
         description: OK
        '400':
         description: Bad Request
        '500':
         description: Internal Server Error OR authorization header must be provided.

  /api/v1/member/edit_profile:
    post:
      summary: edit Profile
      tags:
        - Profile
      requestBody:
        content:
          application/json:
             schema:
               type: object
               properties:
                 id:
                   type: number
                   minLength: 1
                   description: id of profile.
                 aboutMe:
                   type: string
                   minLength: 1
                   description: About me.
                 wallet:
                   type: string
                   minLength: 1
                   description: Wallet.
                 pic:
                  type: string
                  format: 1
                  description: profile pic.
               required:
                 - id
                 - aboutMe
                 - wallet
                 - pic
      security:
       - BearerAuth: []
      responses:
        '200':
         description: OK
        '400':
         description: Bad Request
        '500':
         description: Internal Server Error OR authorization header must be provided.

  /api/v1/member/get_profile:
    post:
      summary: Return profile.
      tags:
        - Profile
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK

  /api/v1/member/changepassword:
    post:
      summary: Update password.
      tags:
        - Profile
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                oldPassword:
                  type: string
                  minLength: 1
                  description: Password to Update.
                password:
                  type: string
                  minLength: 1
                  description: Password to Update.
              required:
                - oldPassword
                - password
      security:
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error OR authorization header must be provided

  /api/v1/member/add_product:
    post:
      summary: Add Products.
      tags:
        - Products
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                sku_code: 
                  type: string
                  description: SKU code
                cover_pic:
                  type: string
                  description: cover picture of product
                name: 
                  type: string
                  description: Product name
                description: 
                  type: string
                  description: Product description
                issue_year: 
                  type: string
                  description: Year of issue
                item_condition: 
                  type: string
                  description: Condition of the item
                catagory: 
                  type: string
                  description: Product category
                varities: 
                  type: string
                  description: Varieties
                city: 
                  type: string
                  description: City
                ruler: 
                  type: string
                  description: Ruler
                denomination: 
                  type: string
                  description: Denomination
                signatory: 
                  type: string
                  description: Signatory
                rarity: 
                  type: string
                  description: Rarity
                specification: 
                  type: string
                  description: Specification
                metal: 
                  type: string
                  description: Metal
                remarks: 
                  type: string
                  description: Remarks
                quantity: 
                  type: string
                  description: Quantity
                custom_url: 
                  type: string
                  description: Custom URL
                video: 
                  type: string
                  description: Video URL
                current_price: 
                  type: string
                  description: Current price
                initial_price: 
                  type: string
                  description: Initial price
                note: 
                  type: string
                  description: Note
                sold: 
                  type: string
                  description: Sold status
                type_series: 
                  type: string
                  description: Type series
                instock: 
                  type: string
                  description: In stock status
                keyword: 
                  type: string
                  description: Keyword
                img: 
                  type: array
                  description: Array of image URLs
                  items:
                    type: string
      #         required: 
      #           - sku_code
      #           - name
      #           - description
      #           - issue_year
      #           - item_condition
      #           - catagory
      #           - varities
      #           - city
      #           - ruler
      #           - denomination
      #           - signatory
      #           - rarity
      #           - specification
      #           - metal
      #           - remarks
      #           - quantity
      #           - custom_url
      #           - current_price
      #           - initial_price
      #           - note
      #           - sold
      #           - type_series
      #           - instock
      #           - keyword
      #           - hidden
      security:  
        - BearerAuth: []
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error OR authorization header must be provided

  /api/v1/member/get_product:
    post:
      summary: Return Products.
      tags:
        - Products
      security:
        - BearerAuth: []
      responses: 
        '200':
          description: OK

  /api/v1/member/buy_request:
    post:
      summary: Add Buy request.
      tags:
        - Trades
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                product_id: 
                  type: string
                  minLength: 1
                  description: product id.
                quantity: 
                  type: string
                  minLength: 1
                  description: quantity.
                price: 
                  type: string
                  minLength: 1
                  description: price.
              required: 
                - id
                - quantity
                - price
      security:
        - BearerAuth: []
      responses: 
        '200':
          description: OK

  /api/v1/member/get_buy_requests:
    post:
      summary: Return all buy_requests.
      tags:
        - Trades
      security:
        - BearerAuth: []
      responses: 
        '200':
          description: OK

  /api/v1/member/bulk_product_data:
    post:
      summary: Add bulk data buy adding csv file.
      tags:
        - Products
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: Select File (CSV).
                
              required: 
                - file
      security:  
        - BearerAuth: []
      responses:
        '200':
        description: OK
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error OR authorization header must be provided
